name: Build-Dev Service

on:
  push:
    branches: [ "*","**", "!main" ]

jobs:
  yarn:
    name: cache node modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        id: yarn-cache-node-modules
        with:
          path: src/frontend/node_modules
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('src/frontend/yarn.lock') }}
      - name: Yarn install if cache is invalid
        if: steps.yarn-cache-node-modules.outputs.cache-hit != 'true'
        working-directory: ./src/frontend
        run: yarn install
  lint:
    name: lint frontend
    runs-on: ubuntu-latest
    needs: [ yarn ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        id: yarn-cache-node-modules
        with:
          path: src/frontend/node_modules
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('src/frontend/yarn.lock') }}
      - name: lint
        working-directory: ./src/frontend
        run: npm run lint
  test_backend:
    name: test backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests
        run: mvn test
  frontend_build:
    name: build frontend
    needs: [ yarn, lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        id: yarn-cache-node-modules
        with:
          path: src/frontend/node_modules
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('src/frontend/yarn.lock') }}
      - name: build vite
        working-directory: ./src/frontend
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: src/frontend/dist
  backend_build:
    name: build backend
    runs-on: ubuntu-latest
    needs: [ frontend_build, test_backend ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/download-artifact@v3
        with:
          name: frontend
          path: ./src/main/resources/META-INF/resources
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build dev with Maven
        run: mvn package -DskipTests -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.container-image.tag=${{ github.sha }} -Dquarkus.container-image.group=${{ secrets.DOCKER_USER }} -Dquarkus.container-image.push=true
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: frontend
  deploy:
    name: deploy
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    needs: [ backend_build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: 'dev-ebooks'
          stack-definition: 'stack-definition.yaml'
          template-variables: >
            {
              "version": "${{ github.sha }}", 
              "username": "${{ secrets.DOCKER_USER }}", 
              "db_username": "${{ secrets.DB_USER }}", 
              "db_password": "${{ secrets.DB_PASSWORD }}",
              "login_salt": "${{ secrets.LOGIN_SALT }}", 
              "admin_username": "${{ secrets.ADMIN_USERNAME }}", 
              "admin_password": "${{ secrets.ADMIN_PASSWORD }}",
              "mount_folder": "/volume1/docker/dev-ebook",
              "port": "1242"
            }
          image: ${{ env.DOCKER_IMAGE_URI }}:${{ env.IMAGE_TAG }}
